// <auto-generated />
using System;
using Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Complexity")
                        .HasColumnType("integer");

                    b.Property<int>("CreatedAt")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer");

                    b.Property<int>("PlaytimeMin")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1bd1bfa-4d38-4d69-a68d-0fd1599095ef"),
                            Complexity = 2,
                            CreatedAt = 0,
                            Description = "A game of trading and building.",
                            ImageUrl = "",
                            MaxPlayers = 4,
                            PlaytimeMin = 60,
                            Title = "Catan"
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.GameCopy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CreatedAt")
                        .HasColumnType("integer");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("GameCopies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1b1b1b1-4d38-4d69-a68d-0fd1599095ef"),
                            CreatedAt = 0,
                            GameId = new Guid("d1bd1bfa-4d38-4d69-a68d-0fd1599095ef")
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CreatedAt")
                        .HasColumnType("integer");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ForcePasswordChange")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = 0,
                            EmailAddress = "admin@test.com",
                            ForcePasswordChange = false,
                            Name = "Admin User",
                            PasswordHash = "admin",
                            Phone = "",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = 0,
                            EmailAddress = "customer@test.com",
                            ForcePasswordChange = false,
                            Name = "Customer User",
                            PasswordHash = "customer",
                            Phone = "",
                            Role = 0
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = 0,
                            EmailAddress = "steward@test.com",
                            ForcePasswordChange = false,
                            Name = "Steward User",
                            PasswordHash = "steward",
                            Phone = "",
                            Role = 1
                        });
                });

            modelBuilder.Entity("Api.Domain.Entities.GameCopy", b =>
                {
                    b.HasOne("Api.Domain.Entities.Game", "Game")
                        .WithMany("GameCopies")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Api.Domain.Entities.Game", b =>
                {
                    b.Navigation("GameCopies");
                });
#pragma warning restore 612, 618
        }
    }
}
